version: '3'
services:
    nginx: 
      container_name: Word-UI
      build:
            context: ../TheWord-UI
            dockerfile: ./WORD-UI-DOCKERFILE-PROD
      image: tobintom/word-ui:latest     
      ports:
      - "80:80"
      - "443:443"
      volumes:
       - /etc/letsencrypt/:/etc/letsencrypt/
       - /usr/share/nginx/html:/usr/share/nginx/html
      networks:
            - theword-network    
    eureka-server:
        container_name: Eureka-server
        build:
            context: ../EurekaServer-service
            dockerfile: ./EUREKA-SERVER-DOCKERFILE
        image: tobintom/eureka-server:latest        
        ports: 
            - "3000:3000"
        environment: 
              SERVER_PORT: 3000
              EUREKA_URL: http://45.79.54.175:3000/eureka/
        networks: 
            - theword-network
    AuthorizationServer-service:
        container_name: Authorization-server
        build:
            context: ../AuthorizationServer-service
            dockerfile: ./AUTH-SERVER-DOCKERFILE
        image: tobintom/authorization-server:latest
        entrypoint: /opt/lib/AuthorizationStartup.sh        
        ports:
            - "4000:4000"
        environment: 
              SERVER_PORT: 4000
              EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:3000/eureka  
              LDAP_URL: ldap://45.79.54.175:389/dc=theword,dc=org
              EUREKA_URL: http://45.79.54.175:3000/eureka/
              CLIENT_NAME: theWord-client
              CLIENT_SECRET: secret
              KEY_STORE_PASS: t0b1nt0m
              KEY_NAME: mykey
              KEY_PASS: t0b1nt0m
              LDAP_ADMIN: CN=admin,DC=theword,DC=org
              LDAP_PASS: t0b1nt0m
        networks:
            - theword-network
        links:
            - eureka-server:eureka-server
        depends_on: 
            - eureka-server
    WordContent-service:
        build:
            context: ../TheWord
            dockerfile: ./WORD-SERVICE-DOCKERFILE
        image: tobintom/wordcontent-service:latest
        entrypoint: /opt/lib/Wordstartup.sh        
        ports:
            - "3010-3014:3010"
        environment: 
              SERVER_PORT: 3010
              EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:3000/eureka
              MONGODB_HOST: 45.79.54.175
              MONGODB_PORT: 37020
              EUREKA_URL: http://45.79.54.175:3000/eureka/
              SWAGGER_AUTH: http://thedigitalword.org:5000/theword
              SWAGGER_ID: theWord-client
              SWAGGER_PASS: secret
              MONGODB_AUTH_DB: admin
              MONGODB_USER: dbadmin
              MONGODB_PASS: t0b1nt0m
              MONGODB_DB: BP
        networks:
            - theword-network
        links: 
            - eureka-server:eureka-server
        depends_on: 
            - eureka-server
    WordMeta-service: 
        build:
            context: ../WordMeta
            dockerfile: ./META-SERVICE-DOCKERFILE
        image: tobintom/wordmeta-service:latest
        entrypoint: /opt/lib/Metastartup.sh        
        ports:
            - "3001-3005:3001"
        environment: 
              SERVER_PORT: 3001
              EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:3000/eureka
              MONGODB_HOST: 45.79.54.175
              MONGODB_PORT: 37020
              EUREKA_URL: http://45.79.54.175:3000/eureka/
              SWAGGER_AUTH: http://thedigitalword.org:5000/theword
              SWAGGER_ID: theWord-client
              SWAGGER_PASS: secret
              MONGODB_AUTH_DB: admin
              MONGODB_USER: dbadmin
              MONGODB_PASS: t0b1nt0m
              MONGODB_DB: BP              
        networks:
            - theword-network
        links: 
            - eureka-server:eureka-server
        depends_on: 
            - eureka-server 
    ZuulServer:
        container_name: ZuulServer
        build:
            context: .
            dockerfile: ZUUL-EDGE-DOCKERFILE
        image: tobintom/zuulserver:latest
        entrypoint: /opt/lib/Zuulstartup.sh                 
        ports:
            - "5000:5000"            
        environment: 
              SERVER_PORT: 5000
              EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:3000/eureka
              EUREKA_URL: http://45.79.54.175:3000/eureka/
        networks:
            - theword-network
        links:
            - eureka-server:eureka-server
        depends_on:
            - eureka-server
networks:
    theword-network: 
        driver: bridge
