FROM openjdk:8-jre-alpine
MAINTAINER TOBIN_TOM

WORKDIR .
COPY ./target/TheWordBatch-1.0.jar /
RUN apt-get update && apt-get install -y cron
ADD crontab /etc/cron.d/simple-cron
RUN chmod 0644 /etc/cron.d/simple-cron
RUN crontab /etc/cron.d/simple-cron
CMD cron

